### ISSUE TITLE
Bump aws-ebs-csi-driver to v1

### ISSUE THREAD

**Issue by lens0021** [femiwiki/nomad#28]
```
$ nomad -v
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)
```

Running the controller failed like the below output even when all volumes are detached and deregistered.

```
[ec2-user@ip-172-31-22-50 jobs]$ nomad alloc logs -stderr 59c81142
I0504 21:37:05.588204       1 driver.go:72] Driver: ebs.csi.aws.com Version: v1.0.0
I0504 21:37:05.588253       1 controller.go:80] [Debug] Retrieving region from metadata service
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12a42e8]

goroutine 1 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0x0, 0x1b52201, 0x40005419e0, 0x0)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/vendor/k8s.io/client-go/kubernetes/clientset.go:395 +0x28
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/cloud.NewMetadata(0x2970000, 0x0, 0x18ef1f6, 0x2f)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/cloud/metadata.go:84 +0xb4
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newControllerService(0x400003a2d0, 0x40004cb620, 0x0, 0x16, 0x400050fe38)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/controller.go:81 +0x150
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver(0x400050ff30, 0x7, 0x7, 0x40004cb4a0, 0x28e3a00, 0x1b522e0)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:92 +0x42c
main.main()
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:46 +0x190
I0504 21:37:27.135472       1 driver.go:72] Driver: ebs.csi.aws.com Version: v1.0.0
I0504 21:37:27.135520       1 controller.go:80] [Debug] Retrieving region from metadata service
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12a42e8]

goroutine 1 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0x0, 0x1b52201, 0x40003abf70, 0x0)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/vendor/k8s.io/client-go/kubernetes/clientset.go:395 +0x28
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/cloud.NewMetadata(0x2970000, 0x0, 0x18ef1f6, 0x2f)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/cloud/metadata.go:84 +0xb4
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newControllerService(0x40000908c0, 0x4000123b60, 0x0, 0x16, 0x400050fe38)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/controller.go:81 +0x150
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver(0x400050ff30, 0x7, 0x7, 0x40001239e0, 0x28e3a00, 0x1b522e0)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:92 +0x42c
main.main()
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:46 +0x190
```

- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/bddf58681d472bca7b91003bef6634226ef93946/pkg/driver/controller.go#L88
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/8b1e568654937ac42ff750fbee79b207d1e63016/vendor/k8s.io/client-go/kubernetes/clientset.go#L395

### Reference(s)

- [Amazon EBS Container Storage Interface (CSI) driver is now generally available
](https://aws.amazon.com/ko/about-aws/whats-new/2021/05/amazon-ebs-container-storage-interface-driver-is-now-generally-available/)

**Comment by lens0021** [comment]
v1.0.3 which fixes the issue is not released on Docker hub.
